/*
 Pre-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be executed before the build script.	
 Use SQLCMD syntax to include a file in the pre-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the pre-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/
SET IDENTITY_INSERT [dbo].[Reports] ON
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (1, N'Population Dashboard', N'ExecutiveDashboard.rdl', N'Dashboard > Population Dashboard')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (2, N'Caseload Dashboard', N'CaseloadDashboard.rdl', N'Dashboard > Caseload Dashboard')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (3, N'Member Demographics', N'MemberDemographics.rdl', N'Members > Demographics')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (4, N'Member Registries', N'DiseaseRegistries.rdl', N'Members > Registries')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (5, N'MemberList (a)', N'MemberList.rdl', N'Members > Member List')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (6, N'MemberList (b)', N'DiseaseRegistriesMemberList.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (7, N'MemberList (c)', N'MemberListAll.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (8, N'Risk Score Comparison', N'HCCComparison.rdl', N'Risk > HCC Score Comparison')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (9, N'High Risk Members', N'TriageMemberCareManagement.rdl', N'Risk > High Risk Members')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (10, N'Prescription Performance', N'PrescriptionPerformance.rdl', N'Prescriptions > Prescription Performance')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (11, N'Members with 10+ Prescriptions', N'HighUtilizationDetailByMedicationCount.rdl', N'Prescriptions > Members with 10+ Medications')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (12, N'Utilization', N'Utilization.rdl', N'Performance > Utilization')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (13, N'YTD Financial', N'Finance.rdl', N'Performance > YTD Financial')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (14, N'Care Management', N'CareManagementPerformance.rdl', N'Performance > Care Management')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (15, N'Metrics', N'MetricList.rdl', N'Performance > Metrics')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (16, N'Provider List', N'ProviderList.rdl', N'Provider > Provider List')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (17, N'Member Detail (IHP)', N'MemberDetailKalamata.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (18, N'Primary Care Clinic Detail', N'PrimaryCareClinicDetail.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (19, N'Member Claim List', N'MemberClaimList.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (20, N'Provider Member Detail', N'ProviderMemberDetail.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (21, N'MemberList (d)', N'MemberListVisits.rdl', N'n/a  (click-thru from Caseload Visit Trend chart)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (22, N'Member Demo HCC Member List', N'MemberDemoHCCMemberList.rdl', N'?')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (23, N'Triage Member Details', N'TriageMemberDetails.rdl', N'n/a (click-thru from TriageMemberCareManagement.rdl)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (24, N'Provider Member Medication Detail', N'ProviderMemberMedicationDetail.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (25, N'Utilization Highest Utilizers', N'UtilizationHighestUtilizers.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (26, N'Utilization Highest Utilizers HEDIS', N'UtilizationHighestUtilizersHEDIS.rdl', N'n/a  (misc click-thru''s)')
INSERT INTO [dbo].[Reports] ([Id], [Report Name], [File Name], [Left Navigation Menu location]) VALUES (27, N'Member Claim Detail', N'MemberClaimDetail.rdl', N'n/a  (misc click-thru''s)')
SET IDENTITY_INSERT [dbo].[Reports] OFF

GO

SET IDENTITY_INSERT [dbo].[Sections] ON
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (1, 1, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (2, 1, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (3, 1, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (4, 1, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (5, 1, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (6, 1, N'Banner', N'Member count matches expected counts from source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (7, 1, N'Banner', N'Clicking member count brings up the Member Demographics page with the appropriate count')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (8, 1, N'Banner', N'Region matches the selected region in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (9, 1, N'Banner', N'Date range matches the dates in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (10, 1, N'Banner', N'Financial totals match the totals in the linked Finance report')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (11, 1, N'Metrics', N'Number of Members Flagged for Risk Metrics matches the counts in source table(s)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (12, 1, N'Metrics', N'Number of Risk Metrics Flagged matches thte counts in source tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (13, 1, N'Metrics', N'Avg % Completion Population Metrics matches source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (14, 1, N'Metrics', N'Clicking "Total" brings up the Metric list for the total population that is available to the current user')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (15, 1, N'Metrics', N'Clicking an agency name brings up the Metrics List page for the selected agency')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (16, 1, N'Registries', N'Applicable registries and member counts (and bar charts) are shown for the current user')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (17, 1, N'Registries', N'Registries that appear in list are supported by SQL data and member counts tie with SQL data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (18, 1, N'Registries', N'Clicking the registry name brings up the registry member list.  (confirm dest page)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (19, 1, N'Registries', N'Clicking "Show All Registries" brings up the Registries page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (20, 1, N'Utilization', N'Actual and Benchmark counts match the expected values from the supporting data tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (21, 1, N'Utilization', N'Actual and Benchmark Charges Per Member match the expected values from the supporting data tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (22, 1, N'Utilization', N'Opportunity column matches with the supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (23, 1, N'Utilization', N'Totals section matches the expected amounts per the source data (Months, Actual Charges, Benchmark Charges)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (24, 1, N'Hospitalization Visit Trend', N'Rolling 12 month view is visible in chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (25, 1, N'Hospitalization Visit Trend', N'Stacked charts for Non-behavioral health and Behavioral health')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (26, 1, N'Hospitalization Visit Trend', N'Data in chart accurately represents the supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (27, 1, N'ED-Only Visit Trend', N'Rolling 12 month view is visible in chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (28, 1, N'ED-Only Visit Trend', N'Stacked charts for Non-behavioral health and Behavioral health')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (29, 1, N'ED-Only Visit Trend', N'Data in chart accurately represents the supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (30, 1, N'Prescription Charges Trend', N'Rolling 12 month view is visible in chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (31, 1, N'Prescription Charges Trend', N'Stacked charts for Non-behavioral health and Behavioral health')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (32, 1, N'Prescription Charges Trend', N'Data in chart accurately represents the supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (33, 1, N'Readmission Trend', N'Rolling 12 month view is visible in chart ')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (34, 1, N'Readmission Trend', N'Data in chart accurately represents the supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (35, 2, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (36, 2, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (37, 2, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (38, 2, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (39, 2, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (40, 2, N'Banner', N'Member count shows the member count from the data tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (41, 2, N'Banner', N'Clicking member count should (?) open the Member Demographics sub page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (42, 2, N'Banner', N'The date shown in the banner should match the date in the report parameters at the top of the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (43, 2, N'Banner', N'"New" patients and "Removed" patient counts should show the correct totals per the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (44, 2, N'Registries', N'Applicable registries appear with member counts that match the counts in the supporting data tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (45, 2, N'Registries', N'Bar charts appear that are representative of the member counts')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (46, 2, N'Registries', N'Clicking the specific registry names takes you to the Member list for the selected registry')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (47, 2, N'Registries', N'Clicking "show all registries" takes you to the Registries sub page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (48, 2, N'Needed Actions', N'Donut charts appear for all appropriate/required needed actions')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (49, 2, N'Needed Actions (donut charts)', N'Shading and labels in chart should match the expected values per the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (50, 2, N'Needed Actions (donut charts)', N'Clicking the charts takes you to the relevant member lists')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (51, 2, N'Population Metrics', N'Chart appears with the top 5 (sorted by completion percent, ascending) population metrics ')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (52, 2, N'Population Metrics', N'Chart columns:  Metric (and ID?), Numerator Denominator, % Complete, Target, Members to Meet Target, CC, Why')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (53, 2, N'Population Metrics', N'Clicking the numerator and denominator takes you to the relevant member lists with the expected counts')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (54, 2, N'Population Metrics', N'Numerator and denominators match the counts in the supporting data tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (55, 2, N'Population Metrics', N'Clicking "show all metrics" takes you to the Metrics sub page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (56, 2, N'Risk Metrics', N'Chart appears with the top 5 (sorted by flagged percent, descending) risk metrics ')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (57, 2, N'Risk Metrics', N'Chart columns:  Metric (and ID?), Numerator Denominator, % Flagged, Target, Members to Meet Target, CC, Why')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (58, 2, N'Risk Metrics', N'Clicking the numerator and denominator takes you to the relevant member lists with the expected counts')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (59, 2, N'Risk Metrics', N'Numerator and denominators match the counts in the supporting data tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (60, 2, N'Risk Metrics', N'Clicking "show all metrics" takes you to the Metrics sub page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (61, 2, N'Visit Trend', N'Chart appears with rolling 6 month view')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (62, 2, N'Visit Trend', N'Behavioral and Non-Behavioral health categories are both split between ED and Hosp categories, and represented on chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (63, 2, N'Visit Trend', N'Detail in chart matches the appropriate source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (64, 2, N'Readmission Trend', N'Chart appears with rolling 6 month view')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (65, 2, N'Readmission Trend', N'Detail in chart matches the appropriate source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (66, 3, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (67, 3, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (68, 3, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (69, 3, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (70, 3, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (71, 3, N'Headers', N'Headers reflect the values in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (72, 3, N'Member Age Distribution graph', N'Histogram graph by age bins is visible and consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (73, 3, N'Member Age Distribution graph', N'Member counts are visible on the various chart bars')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (74, 3, N'Member County Distribution', N'Pie chart is visible and consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (75, 3, N'Member County Distribution', N'Pie chart legend is formatted appropriately')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (76, 3, N'PCP/Assigned Provider Region', N'Member counts and %''s by region are correctly displayed in chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (77, 3, N'Top 20 Member PCP Distribution', N'Bar chart/Histogram of top PCP''s is displayed')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (78, 3, N'Top 20 Member PCP Distribution', N'Clicking a bar will open the PrimaryCareClinicDetail.rdl for the appropriate primary care clinic')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (79, 3, N'Risk Scores chart', N'Period listed matches the period in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (80, 3, N'Risk Scores chart', N'Data listed in chart is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (81, 3, N'Spend vs Member graph', N'Chart is visible and data series are appropriately labeled')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (82, 3, N'Spend vs Member graph', N'Data is consistent with underlying source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (83, 3, N'Member Month Breakdown chart', N'Data in chart is consistent ith underlying source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (84, 3, N'Member Month Breakdown graph', N'Graph is visible and appropriately labeled')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (85, 3, N'Member Month Breakdown graph', N'Data in graph is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (86, 4, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (87, 4, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (88, 4, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (89, 4, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (90, 4, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (91, 4, N'Registry $/Count Graph', N'All appropriate registries appear on graph')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (92, 4, N'Registry $/Count Graph', N'Registry counts and charges display the expected values per the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (93, 4, N'Registry Member Counts Chart', N'All appropriate registries appear on chart ')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (94, 4, N'Registry Member Counts Chart', N'Clicking the "+" beside a registry displays a list of subregistries')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (95, 4, N'Registry Member Counts Chart', N'Current month and prior month are shown (and current month matches the "End period" report parameter)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (96, 4, N'Registry Member Counts Chart', N'Registry counts match the expected counts per the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (97, 4, N'Registry Member Counts Chart', N'Clicking a registry in the chart takes you to the member list for the selected registry (and counts match on destination page)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (98, 4, N'Member Disease Count Breakdown Chart', N'Member counts and percents are displayed by disease-count bins.')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (99, 5, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (100, 5, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (101, 5, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (102, 5, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (103, 5, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (104, 5, N'Chart', N'Patients appearing in list are appropriate for the selections specified in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (105, 5, N'Chart', N'Appropriate columns are visible and populated according to the source data (** get updated column list)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (106, 5, N'Chart', N'Clicking a patientID takes the user to the patient IHP page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (107, 5, N'Header', N'"showing records 0 to 100 of xx" message is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (108, 5, N'Prev 100 & Next 100 arrows', N'Clicking arrows has intended functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (109, 5, N'Excel Export', N'Excel export works as designed')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (110, 6, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (111, 6, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (112, 6, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (113, 6, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (114, 6, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (115, 6, N'Chart', N'Patients appearing in list are appropriate for the selections specified in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (116, 6, N'Chart', N'Appropriate columns are visible and populated according to the source data (** get updated column list)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (117, 6, N'Chart', N'Clicking a patientID takes the user to the patient IHP page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (118, 6, N'Header', N'"showing records 0 to 100 of xx" message is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (119, 6, N'Prev 100 & Next 100 arrows', N'Clicking arrows has intended functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (120, 6, N'Excel Export', N'Excel export works as designed')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (121, 7, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (122, 7, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (123, 7, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (124, 7, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (125, 7, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (126, 7, N'Chart', N'Patients appearing in list are appropriate for the selections specified in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (127, 7, N'Chart', N'Appropriate columns are visible and populated according to the source data (** get updated column list)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (128, 7, N'Chart', N'Clicking a patientID takes the user to the patient IHP page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (129, 7, N'Header', N'"showing records 0 to 100 of xx" message is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (130, 7, N'Prev 100 & Next 100 arrows', N'Clicking arrows has intended functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (131, 7, N'Excel Export', N'Excel export works as designed')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (132, 8, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (133, 8, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (134, 8, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (135, 8, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (136, 8, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (137, 8, N'Main chart', N'Appropriate columns are visible and populated (check with P.O.)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (138, 8, N'Main chart', N'HCC scores for the specified date range are visible tie with the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (139, 8, N'Main chart', N'HCC score for the specified comparable period is visible and ties with the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (140, 8, N'Main chart', N'Claim count YTD is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (141, 8, N'Main chart', N'Premium claims opportunity YTD is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (142, 8, N'Main chart', N'Med count ties with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (143, 8, N'Main chart', N'Validate data in other columns')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (144, 8, N'Main chart', N'Clicking a patientID takes you to the member detail page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (145, 8, N'Excel export', N'Excel export works')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (146, 8, N'Prev 100 and Next 100 arrows', N'Arrows appear and function properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (147, 8, N'"Showing records x to x of x"', N'Showing records message appears properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (148, 9, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (149, 9, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (150, 9, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (151, 9, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (152, 9, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (153, 9, N'Main Chart', N'Chart appears with top 50 of members with triggers')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (154, 9, N'Main Chart', N'Members shown in chart align with the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (155, 9, N'Main Chart', N'HCC scores in chart align with the source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (156, 9, N'Main Chart', N'Clicking a patientID takes you to the member detail page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (157, 9, N'Triage Algorithm pdf', N'Clicking the pdf link opens up the appropriate pdf page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (158, 10, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (159, 10, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (160, 10, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (161, 10, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (162, 10, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (163, 10, N'Headers', N'Headers at top of page accurately reflect the report parameters (period, region, PCP clinic, etc)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (164, 10, N'Top 50 Volume graph (left graph)', N'12 months of volume data appear in chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (165, 10, N'Top 50 Volume graph (left graph)', N'Chart data aligns with underlying source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (166, 10, N'Drug chart (lower left chart)', N'Top 50 drugs (based on number of prescriptions) are shown and sorted/desc by number of prescriptions')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (167, 10, N'Drug chart (lower left chart)', N'Detail shown ties with the detail from the source tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (168, 10, N'Total Paid/Allowed graph (right)', N'12 months of drug paid/allowed data appears in chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (169, 10, N'Total Paid/Allowed graph (right)', N'Chart data aligns with underlying source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (170, 10, N'Drug chart (lower right chart)', N'Top 50 drugs (based on price per Rx) are shown and sorted/desc by print per Rx')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (171, 10, N'Drug chart (lower right chart)', N'Detail shown ties with the detail from the source tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (172, 11, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (173, 11, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (174, 11, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (175, 11, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (176, 11, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (177, 11, N'Headers', N'Headers at top of page accurately reflect the report parameters (period, region, PCP clinic, etc)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (178, 11, N'Main Chart', N'The required fields are visible and accurately reflect the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (179, 11, N'Main Chart', N'Click-thru of PatientID takes you to the appropriate IHP')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (180, 12, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (181, 12, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (182, 12, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (183, 12, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (184, 12, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (185, 12, N'Headers', N'Headers at top of page accurately reflect the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (186, 12, N'Inpatient chart', N'Required columns are visible and populated')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (187, 12, N'Inpatient chart', N'Data in chart ties with data from source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (188, 12, N'OP/Professional chart', N'Required columns are visible and populated')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (189, 12, N'OP/Professional chart', N'Data in chart ties with data from source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (190, 12, N'HEDIS Selected Procedures chart', N'Required columns are visible and populated')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (191, 12, N'HEDIS Selected Procedures chart', N'Data in chart ties with data from source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (192, 12, N'Bed Days Per 1000 graph', N'Graph displays 12 months of data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (193, 12, N'Bed Days Per 1000 graph', N'Data in graph ties with data from source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (194, 12, N'Bed Days Per 1000 graph', N'Legend is visible and properly formatted')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (195, 12, N'Admits per 1000 graph', N'Graph displays 12 months of data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (196, 12, N'Admits per 1000 graph', N'Data in graph ties with data from source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (197, 12, N'Admits per 1000 graph', N'Legend is visible and properly formatted')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (198, 12, N'Readmission Rate graph', N'Graph displays 12 months of data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (199, 12, N'Readmission Rate graph', N'Data in graph ties with data from source table')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (200, 12, N'Readmission Rate graph', N'Legend is visible and properly formatted')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (201, 13, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (202, 13, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (203, 13, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (204, 13, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (205, 13, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (206, 13, N'P&L Chart', N'Revenues and expenses are visible and can be traced back to source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (207, 13, N'P&L Chart', N'Spot checking of summary arithmetic ')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (208, 13, N'Primary Clinic Chart', N'All relevant PCP/Assigned clinics are visible in the chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (209, 13, N'Primary Clinic Chart', N'Data in chart ties with the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (210, 13, N'Primary Clinic Chart', N'Clicking on a PCP/clinic name takes you to the appropriate PrimaryCareClinicDetail.rdl page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (211, 14, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (212, 14, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (213, 14, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (214, 14, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (215, 14, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (216, 14, N'Utilization and PMPM graph', N'Paid PMPM and Claim Count data series are visible on the chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (217, 14, N'Utilization and PMPM graph', N'Data in chart is consistent with supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (218, 14, N'Month Savings Trend graph', N'Savings data series is visible in chart')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (219, 14, N'Month Savings Trend graph', N'Savings data series is consistent with supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (220, 14, N'Change in ER and Visits PMPM graph', N'Data series is consistent with supporting data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (221, 15, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (222, 15, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (223, 15, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (224, 15, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (225, 15, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (226, 15, N'Population Metrics', N'ID, Metric, Numerator, Denominator, % Completed, Target Members to Meet Target columns are visible and formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (227, 15, N'Population Metrics', N'Data in chart is consistent with data in source tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (228, 15, N'Risk Metrics', N'ID, Metric, Numerator, Denominator, % Completed, Target Members to Meet Target columns are visible and formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (229, 15, N'Risk Metrics', N'Data in chart is consistent with data in source tables')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (230, 16, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (231, 16, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (232, 16, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (233, 16, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (234, 16, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (235, 16, N'Top 20 Member PCP graph', N'20 PCP/Clinics are listed, in order of descending membership, across the graph')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (236, 16, N'Top 20 Member PCP graph', N'Clicking the various PCP/clinics in the chart will open the appropriate PrimaryCareClinicDetail.rdl ')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (237, 16, N'PCP/Assigned Provider Region chart', N'PCP''s are listed (by patient count, descending order)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (238, 16, N'PCP/Assigned Provider Region chart', N'Data in chart is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (239, 17, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (240, 17, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (241, 17, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (242, 17, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (243, 17, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (244, 17, N'Member Info', N'The appropriate member data is visible and consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (245, 17, N'ED/Hospitalization Timeline', N'Timeline is visible and formatted correctly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (246, 17, N'ED/Hospitalization Timeline', N'Detail in timeline is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (247, 17, N'Metabolic Screening', N'The distinct count of metabolic screening tests is visible in parentheses and is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (248, 17, N'Metabolic Screening', N'Click thru functionality??')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (249, 17, N'Population Metrics', N'Relevant population metrics are visible and the count in parentheses is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (250, 17, N'Population Metrics', N'The red/green indicator beside the population metrics is correct ')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (251, 17, N'Population Metrics', N'Clicking the CC hyperlink opens the correct CC detail page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (252, 17, N'Population Metrics', N'The population metric data is consistent with the underlying source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (253, 17, N'Risk Metrics', N'Relevant risk metrics are visible and the count in parentheses is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (254, 17, N'Risk Metrics', N'Clicking the CC hyperlink opens the correct CC detail page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (255, 17, N'Risk Metrics', N'The risk metric data is consistent with the underlying source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (256, 17, N'Disease Registries', N'The count in parentheses of the disease registries is consistent with the listing of disease registries for the sample patient')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (257, 17, N'Medications', N'The count in parentheses of the medications is consistent with the listed medications')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (258, 17, N'Medications', N'Clicking the "Current" or "2 Year" buttons has the expected effect on the listed medications (and the count of medications in parentheses)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (259, 17, N'Medications', N'The chart displays the expected columns/data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (260, 17, N'Medications', N'The data in the columns is consistent with the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (261, 17, N'Claims', N'Claims count in parentheses is consistent with underlying source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (262, 17, N'Claims', N'Clicking the "Show All Claims" button takes the user to the MemberClaimList.rdl (with the appropriate/expected number of claims listed)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (263, 18, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (264, 18, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (265, 18, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (266, 18, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (267, 18, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (268, 18, N'Main chart', N'Sample primary provider records are visible and consistent with the source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (269, 18, N'Main chart', N'Clicking the PCP name opens the ProviderMemberDetail.rdl and passes the correct parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (270, 19, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (271, 19, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (272, 19, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (273, 19, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (274, 19, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (275, 19, N'Main chart', N'Relevant columns are visible and populated')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (276, 19, N'Main chart', N'Claim count in chart "footer" (at top) is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (277, 19, N'Main chart', N'Detail in chart is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (278, 20, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (279, 20, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (280, 20, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (281, 20, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (282, 20, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (283, 20, N'Main Chart', N'Members for the specified provider are listed')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (284, 20, N'Main Chart', N'Relevant columns are visible and data is consistent with source data')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (285, 21, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (286, 21, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (287, 21, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (288, 21, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (289, 21, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (290, 21, N'Chart', N'Patients appearing in list are appropriate for the selections specified in the report parameters')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (291, 21, N'Chart', N'Appropriate columns are visible and populated according to the source data (** get updated column list)')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (292, 21, N'Chart', N'Clicking a patientID takes the user to the patient IHP page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (293, 21, N'Header', N'"showing records 0 to 100 of xx" message is correct')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (294, 22, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (295, 22, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (296, 22, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (297, 22, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (298, 22, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (299, 23, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (300, 23, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (301, 23, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (302, 23, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (303, 23, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (304, 24, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (305, 24, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (306, 24, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (307, 24, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (308, 24, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (309, 25, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (310, 25, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (311, 25, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (312, 25, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (313, 25, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (314, 26, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (315, 26, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (316, 26, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (317, 26, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (318, 26, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (319, 27, N'Report Parameters', N'All of the required minimum parameters are available in the rdl file')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (320, 27, N'Report Parameters', N'Parameters at the top of the page should be formatted properly')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (321, 27, N'Report Parameters', N'Parameters are pre-populated as needed per the application functionality')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (322, 27, N'Report Parameters', N'Updating the various report parameters affects the detail on the page')
INSERT INTO [dbo].[Sections] ([Id], [Report ID], [Section], [Description]) VALUES (323, 27, N'Left Nav Bar', N'Navigation bar on the left of the page is visible, formatted correctly and is functional')
SET IDENTITY_INSERT [dbo].[Sections] OFF
