//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeTestDBClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MainMenu()
        {
            this.MainMenuSubMenus = new HashSet<MainMenuSubMenu>();
        }
    
        public int MainMenuID { get; set; }
        public int Active { get; set; }
        public string DisplayLabel { get; set; }
        public string ReportName { get; set; }
        public int MenuSortOrder { get; set; }
        public string SelectedFillColor { get; set; }
        public string NotSelectedFillColor { get; set; }
        public string SelectedFontColor { get; set; }
        public string NotSelectedFontColor { get; set; }
        public string FontWeight { get; set; }
        public string ImageMimeType { get; set; }
        public byte[] SelectedImageBits { get; set; }
        public byte[] NotSelectedImageBits { get; set; }
        public Nullable<bool> HasSubMenu { get; set; }
        public byte[] ExpandNotSelectedImageBits { get; set; }
        public byte[] ExpandSelectedImageBits { get; set; }
        public byte[] CollapseNotSelectedImageBits { get; set; }
        public byte[] CollapseSelectedImageBits { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainMenuSubMenu> MainMenuSubMenus { get; set; }
    }
}
