//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeTestDBClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainMenuSubMenu
    {
        public int MainMenuSubMenuID { get; set; }
        public int MainMenuID { get; set; }
        public string SubMenuDisplayLabel { get; set; }
        public string ReportName { get; set; }
        public int SubMenuSortOrder { get; set; }
        public string SelectedFillColor { get; set; }
        public string NotSelectedFillColor { get; set; }
        public string SelectedFontColor { get; set; }
        public string NotSelectedFontColor { get; set; }
        public string FontWeight { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
    }
}
