//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmokeTestDBClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmokeTestsEntities : DbContext
    {
        public SmokeTestsEntities()
            : base("name=SmokeTestsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Evaluator> Evaluators { get; set; }
        public virtual DbSet<Release> Releases { get; set; }
        public virtual DbSet<Report_Evaluation> Report_Evaluations { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Section_Evaluation> Section_Evaluations { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<Status> Status { get; set; }
    }
}
